[package]
name = "search_trie"
version = "0.1.0"
authors = ["schulace <alex.schuler@hive.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
